services:
  
  redis:
    container_name: bpics-redis
    image: redis
    profiles:
      - production
  
  server:
    container_name: bpics-server
    build:
      context: ./BlissSlideshow
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./build:/app/build
    command: /start-server.sh
    profiles:
      - production

  frontend-build:
    container_name: bpics-frontend-build
    build:
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./build:/src/build
    command: npx webpack --config /src/webpack.config.js
    profiles:
      - build

  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}